### ISSUE TITLE
能否设置一级缓存为内存 二级为disk？

### ISSUE THREAD

**Issue by wujingke** [TeaOSLab/EdgeAdmin#1]
能否设置一级缓存为内存 二级为disk？

**Comment by iwind** [comment]
谢谢你的建议， 现在实现的是最基础的缓存机制，逐渐会优化。

**Comment by wujingke** [comment]
https://github.com/buraksezer/olric
https://github.com/pquerna/cachecontrol
这两个可以参考一下

**Comment by iwind** [comment]
0.0.12里已经实现。
