### ISSUE TITLE
功能建议:希望增加一个批量修改网站的功能

### ISSUE THREAD

**Issue by suomalihaicao** [TeaOSLab/EdgeAdmin#10]
修改一个网站服务功能，希望可以批量把这个服务修改应用到对应网站

**Comment by suomalihaicao** [comment]
比如说http里面的自动跳转https，想统一应用，就得一个一个去改，如果有个批量功能就太nice了，谢谢

**Comment by immoke** [comment]
支持，或者增加一个复制某网站模版的功能也行，每个都要一步一步调整，确实效率不高。感谢作者无私奉献。
