### ISSUE TITLE
缓存的问题，首页用伪静态，但是无论用什么都缓存不了

### ISSUE THREAD

**Issue by yishuge123** [TeaOSLab/EdgeAdmin#14]
缓存的问题，首页用伪静态，但是无论用什么都缓存不了

**Comment by iwind** [comment]
可以在浏览器上或者访问日志里查看X-Cache，里面有具体的原因，参考：https://goedge.cn/docs/Server/Cache.md#%E7%BC%93%E5%AD%98%E7%8A%B6%E6%80%81

**Comment by yishuge123** [comment]
X-Cache: BYPASS&nbsp; 都是这个，我用精确匹配，直接输入网站地址，用正则：www.([a-z0-9\-]+)\.(com|net|cn|vip|info|cc|xyz|top)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TeaOSLab/EdgeAdmin] 缓存的问题，首页用伪静态，但是无论用什么都缓存不了 (Issue #14)





 
可以在浏览器上或者访问日志里查看X-Cache，里面有具体的原因，参考：https://goedge.cn/docs/Server/Cache.md#%E7%BC%93%E5%AD%98%E7%8A%B6%E6%80%81

**Comment by iwind** [comment]
URL精准匹配中不包含域名，

**Comment by yishuge123** [comment]
能给个匹配首页缓存的正则么，因为没有带index.html

**Comment by iwind** [comment]
请仔细阅读表单中每个参数的说明。

**Comment by iwind** [comment]
选择条件类型：URL精准匹配
URL完整路径：/

**Comment by iwind** [comment]
这个参数名称可能会产生误导，后面考虑改成叫“请求路径”，可能会好一些。

另外如果是我们的用户可以加群更方便与大家交流： https://goedge.cn/community

**Comment by yishuge123** [comment]
好的，我自己研究下
