### ISSUE TITLE
功能优化建议：平台数据库容易出现瓶颈

### ISSUE THREAD

**Issue by TopxData** [TeaOSLab/EdgeAdmin#16]
平台数据库只能对接单台，如果业务量过大时，会导致数据库性能不足。测试对接proxysql做读写分离，发现无法对接上平台，希望增加对mysql中间件的支持，以实现后端数据库的高可靠性。

**Comment by iwind** [comment]
GoEdge对mysql中间件没有限制，因为在GoEdge里只是正常的连接和操作。如果某个中间件不工作，可以补充一些更详细的信息方便我们分析。
