### ISSUE TITLE
功能优化建议：日志数据库负载不均衡

### ISSUE THREAD

**Issue by TopxData** [TeaOSLab/EdgeAdmin#17]
目前系统增加了两台日志数据库，发现一台数据库写入量很大，另一台写入量特别小。大概占比为 8:2
![image](https://user-images.githubusercontent.com/68526709/183294475-2c498b26-6a0b-4542-966e-fcd0fc0462b5.png)

**Comment by iwind** [comment]
在先前版本中已经解决
