### ISSUE TITLE
【提问】单个集群内不同网站是否可以应用多种WAF策略？

### ISSUE THREAD

**Issue by luckykeeper** [TeaOSLab/EdgeAdmin#18]
试用了一下，感觉还是挺好用的
但是发现单个集群似乎只能应用一个WAF规则，不知道是我没有找到还是没有做这样的功能
如果是我没有找到麻烦指点一下怎么弄，如果是没有做这样的功能希望下版做一个

应用举例：
> 同一个集群内的多个网站，针对不同网站，需要应用不同的WAF策略，目前似乎一个集群只能应用一种策略？网站内没有看到WAF策略的更改选项

版本 0.5.1 开源版本

**Comment by iwind** [comment]
现在同个集群下的网站只能使用一种WAF策略；单个网站如果需要定制规则的话，可以在网站服务设置—WAF里添加。

**Comment by luckykeeper** [comment]
感谢解答~
我去看了一下，好像说的是这个对吧
![image](https://user-images.githubusercontent.com/34579433/185026636-193eb969-54e5-42e9-a793-a54932346a4f.png)
如果我想要实现预置的部分WAF规则，就把里面的正则抄到这个地方是吗？我理解的对嘛？
感觉如果是这样的话还是比较麻烦，希望可以同集群可以加入多种策略然后在加入网站的时候给个选项从中选择一种

**Comment by iwind** [comment]
单个集群下用多个策略不容易管理，暂时不考虑，先关了。
