### ISSUE TITLE
更换集群域名请不要删除老记录

### ISSUE THREAD

**Issue by JusufUs** [TeaOSLab/EdgeAdmin#24]
因为新记录生效需要时间，现在更换域名会立即删除老集群的DNS所有记录，这样会造成空挡时间
或者说可以选择是否删除老记录，还有个中间方案，就是单个集群可以用多个域名

**Comment by iwind** [comment]
新记录生效需要时间，同样老记录失效也会需要时间，所以大致是差不多的。这里面没有完美的方案，因为无论延时多少，客户端DNS都会有生效时间的问题；另外，如果不删除，给其他用户的运维的人员的感觉这是一个Bug，因为网站迁移了，解析并没变。
