### ISSUE TITLE
当反代Websocket协议的时候节点服务器统计连接数不正确。

### ISSUE THREAD

**Issue by vasma1984** [TeaOSLab/EdgeAdmin#28]
![Snipaste_2024-01-16_01-39-48](https://github.com/TeaOSLab/EdgeAdmin/assets/119785562/05d00214-e67b-4294-9b8d-3fbbd50cbeb0)

如图其实这个节点只有300左右的连接，但是当反代Websocket协议的时候节点服务器统计连接数不正确。
我想这里的连接数是不是显示的了，一段时间内的http请求数量了？

**Comment by iwind** [comment]
谢谢反馈，我们将会尽快测试验证是否有这个问题。

**Comment by iwind** [comment]
此问题将会在v1.3.3版本中修复
