### ISSUE TITLE
能否针对节点可以加入到多个集群提升复用率

### ISSUE THREAD

**Issue by eddytom73** [TeaOSLab/EdgeAdmin#3]
能否针对节点可以加入到多个集群提升复用率

**Comment by iwind** [comment]
现在单个节点不能加入多个集群的原因：
1、集群之间的配置可能冲突，比如缓存策略、WAF策略等
2、集群下的服务可能冲突，比如分属两个集群下的TCP转发服务的端口可能一样，会导致其中一个端口无法启动

我正在思考“借用”节点这个概念，可以在集群中借用别的集群的节点来部署服务，但是不同步配置。这个会在未来一两个版本内实现。

**Comment by iwind** [comment]
在 v0.2.6 中解决了此问题。
