### ISSUE TITLE
【提问】请问怎么设置备用API跟数据库

### ISSUE THREAD

**Issue by GMxx1688** [TeaOSLab/EdgeAdmin#30]
例如主API节点跟管理平台断网 CDN节点能从备用的API读取备用数据库源站地址继续缓存网站

**Comment by iwind** [comment]
1. 边缘节点和API节点失联后，边缘节点仍然能正常提供服务和缓存内容
2. 目前没有备用API节点可以设置

**Comment by GMxx1688** [comment]
多谢解答，边缘节点和API节点失联后，边缘节点仍然能正常缓存内容就行。
