### ISSUE TITLE
我应该如何排查故障呢？不停的有节点提示：已处于离线状态，请检查节点是否异常

### ISSUE THREAD

**Issue by JesseWang2022** [TeaOSLab/EdgeAdmin#31]
总有节点不停提示这个问题，节点卡死之类的，特别累人，不停的重启也只是暂时解决，请教老师们，我应该如何排查故障呢？

**Comment by iwind** [comment]
如有问题，请在群里问。

关于你这个问题，请参考：https://goedge.cn/docs/Node/QA.md?v=1#%E8%8A%82%E7%82%B9%E5%90%AF%E5%8A%A8%E6%AD%A3%E5%B8%B8%E4%BD%86%E6%98%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2%E6%98%BE%E7%A4%BA%E7%A6%BB%E7%BA%BF
