### ISSUE TITLE
【建议】几个小功能的建议

### ISSUE THREAD

**Issue by immoke** [TeaOSLab/EdgeAdmin#32]
1、WAF策略中，如果是验证码多次失败，会自动添加到系统黑名单，能否在WAF中指定添加到哪个公共黑名单里；
    比如说，针对爬虫，我希望是先弹出验证码，如果是连续失败多少次，然后自动添加到爬虫分组的黑名单里，这样以后也好管理。

2、是否可以增加一个类似“灰名单”的分组，这个分组只是用来搜集IP，而不是做拦截。
    比如说，我需要观测访问我网站的，使用Edge浏览器的用户，现在只能识别后放到白名单里，然后有些恶意的爬虫会伪造Edge的useragent，然后我的其他规则（比如说 目录探测）就完全失效了。如果放到黑名单里，误伤又比较大。然后因为一个服务器，或者所属集群只能一个waf规则，其他站还是需要正常的拦截的，也不能改成观察模式。

以上，感谢。

**Comment by iwind** [comment]
1. 会增加管理复杂度，暂时不加
2. 可以将规则集中的动作设置为“标签”

**Comment by iwind** [comment]
暂不处理

**Comment by iwind** [comment]
将会在1.3.9版本中加入IP“灰名单”。
