### ISSUE TITLE
【建议】关于主控和节点之间的ssh连接

### ISSUE THREAD

**Issue by corcassianwalnut** [TeaOSLab/EdgeAdmin#33]
请问能否考虑让主控使用如socks5或跳板机对节点进行连接

**Comment by iwind** [comment]
首先，主控不会主动连接节点，而是节点主动连接主控的；其次，如果你的节点和主控（API节点）连接较不稳定，可以参考这里：https://goedge.cn/docs/APINode/Forward.md

**Comment by iwind** [comment]
> > 合作
> 
> 主控和节点的ssh连接呢? 远程安装和ssh启动/关闭什么的

你仍然可以使用“中转”反向转发ssh端口。
