### ISSUE TITLE
批量操作

### ISSUE THREAD

**Issue by eddytom73** [TeaOSLab/EdgeAdmin#4]
例如源需要进行更换或者新增 但是此源的服务有100个甚至更多，有批量操作的考虑吗?

**Comment by iwind** [comment]
你是说可能大量的服务在使用同一个源站吗？这个时候不使用同一个服务的考虑是？

**Comment by eddytom73** [comment]
因为添加的前后时间顺序不一样 需要不同服务名来区分不同区域

**Comment by eddytom73** [comment]
例如 
A域名负责华南
B域名负责西南
C域名负责东北

**Comment by eddytom73** [comment]
在业务上需要人为的区分一下 这样才能看到服务就知道此域名是负责那一块的

**Comment by iwind** [comment]
v0.3.1开始可以在服务分组中设置全局设置，设置后，此分组下的所有服务自动应用此设置。
