### ISSUE TITLE
想能更直观的看到所有边缘节点的负载情况

### ISSUE THREAD

**Issue by wanglin741963** [TeaOSLab/EdgeAdmin#8]
而且在节点列表里的信息有点少，要点击去详情才能看到连接数那些。想在节点列表里看到尽量多的负载情况。

**Comment by iwind** [comment]
因为在节点数比较多的时候， 实时更新连接数、流量等数据比较耗系统资源，所以暂时还没放上。不过，仍然会在后续版本中以最最高效的方式实现。

**Comment by iwind** [comment]
在最近的版本中已经实现。
