### ISSUE TITLE
网站服务里面，右上角，希望增加一个下拉菜单，可以一次性显示所有网站，每次修改一个网站，都必须返回网站，再重新点击，太繁琐了

### ISSUE THREAD

**Issue by suomalihaicao** [TeaOSLab/EdgeAdmin#9]
网站服务里面，右上角，希望增加一个下拉菜单，可以一次性显示所有网站，每次修改一个网站，都必须返回网站，再重新点击，太繁琐了
![image](https://user-images.githubusercontent.com/87162168/147770796-24ad71c3-d2d5-4725-9ed6-0c92df655904.png)

**Comment by iwind** [comment]
已经可以在顶部服务名称后面进行切换，所以此issue关闭。
